jauth-url: 
  http://182.92.105.202:8440/jauth
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.92.105.202:3306/jauth
    username: jauth
    password: jauth
