server:
  port: @port@
  context-path: /acrm
spring:
  profiles:
    active: @env@
  application:
    name: cpacrm
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
  boot:
    admin:
      url: "${jauth-url}/sba/"
security: 
  basic:
    enabled: false
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: "${jauth-url}/eureka/"
  instance:
    leaseExpirationDurationInSeconds: 1
    leaseRenewalIntervalInSeconds: 1
info:
  app:  
    name: "cpacrm"  
    description: "360客户视图接口"  
version: "1.0.0"  
