jauth-url: 
  http://localhost:8440/jauth
cust_id:
  cust_id
spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.1.245.175:3306/cocdev?useUnicode=true&characterEncoding=utf-8
      username: cocdev
      password: cocdev
      maxActive: 300
      maxWait: 500
      maxIdle: 30
      minIdle: 10
      initialSize: 10
      testOnBorrow: false
      removeAbandoned: true
      removeAbandonedTimeout: 3600
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 180000
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.1.245.175:3306/cocdev?useUnicode=true&characterEncoding=utf-8
      username: cocdev
      password: cocdev
      maxActive: 300
      maxWait: 500
      maxIdle: 30
      minIdle: 10
      initialSize: 10
      testOnBorrow: false
      removeAbandoned: true
      removeAbandonedTimeout: 3600
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 180000  
cache:
  loadDataScope: DimtableInfoDaoImpl
  isDimtableCached: true
context:
  listener:
    classes: com.asiainfo.cp.acrm.ApplicationStartup
    