server:
  port: 8442
  context-path: /
spring:
  profiles:
    active: cp-yw
  application:
    name: cpacrm
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
  boot:
    admin:
      url: "${jauth-url}/sba/"
security: 
  basic:
    enabled: false
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: "${jauth-url}/eureka/"
  instance:
    leaseExpirationDurationInSeconds: 1
    leaseRenewalIntervalInSeconds: 1
