spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.3.232.106:3306/ywjauth?useUnicode=true&characterEncoding=utf-8
    username: ywjauth
    password: Ywjauth_123
