jauth-url: 
  http://10.3.232.192:80/jauth
cust_id:
  cust_sub_code
spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.3.232.105:3306/acrm_coc?useUnicode=true&characterEncoding=utf-8
      username: coc
      password: 1qaz2wsx
      maxActive: 300
      maxWait: 1800
      maxIdle: 30
      minIdle: 10
      initialSize: 10
      testOnBorrow: false
      removeAbandoned: true
      removeAbandonedTimeout: 3600
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction- -millis: 180000
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://ads-acrm-cm360-fe11ca59.cn-beijing-bjyz-am92001-a.postcloud.cn:10069/ads_acrm_cm360?useUnicode=true&characterEncoding=utf-8
      username: c90702QfZJrCrLPf
      password: TbMEImohsKrRUrYQjpAUAfhZK2eXN2
      maxActive: 300
      maxWait: 1800
      maxIdle: 30
      minIdle: 10
      initialSize: 10
      testOnBorrow: false
      removeAbandoned: true
      removeAbandonedTimeout: 3600
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 180000  
cache:
  isDimtableCached: false
context:
  listener:
    classes: com.asiainfo.cp.acrm.ApplicationStartup